### ISSUE TITLE
Submit to OPAM repository

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [prepor/ocaml-edn#1]
Hi,

I think it would be nice to have this in OPAM since other packages could easily depend on this, for example https://github.com/jonase/eq

Also, thanks for writing an EDN parser for OCaml, I was thinking of making one myself, one less thing to do is always appreciated :)

**Comment by prepor** [comment]
Hello! Thank you! Please give me a few days ;)

**Comment by prepor** [comment]
https://github.com/ocaml/opam-repository/pull/6805

**Comment by Leonidas-from-XIV** [comment]
Thank you!

**Comment by prepor** [comment]
merged
