### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by jonase** [prepor/ocaml-edn#7]
@prepor would you be open to adding some unit tests? I tried a [ounit](http://ounit.forge.ocamlcore.org/) setup [in this branch](https://github.com/jonase/ocaml-edn/commit/cb6d483baf51feb0045303867b1ad55cd658d44a) but I'm not sure if the setup is correct. I can run the unit tests with `make test && ./test.native`.

I can open a PR if this is something you would like to see added.

**Comment by Leonidas-from-XIV** [comment]
Wouldn't generative tests make more sense? Especially the round-trip property would be something worth testing.

**Comment by jonase** [comment]
Good point, definitely worth considering! Do you know how this is done in ocaml? I found [iTeML / qtest](https://github.com/vincent-hugot/iTeML#randomized-tests-for-quickcheck) but there might be other approaches as well.

For a "complete" test suite I don't think it's enough to only test the print/read round trip as it will only test edn's that the printer produces. One [example](https://github.com/edn-format/edn#general-considerations) could be 

> The delimiters `{ } ( ) [ ]` need not be separated from adjacent elements by whitespace.

 I.e. the printer wouldn't produce the valid edn string `[1[bar]]`. Other examples are comments and the discard reader macro `#_`.

**Comment by Leonidas-from-XIV** [comment]
I used to like [qcheck](https://github.com/c-cube/qcheck) but as it was merged into qtest I guess that's currently the best solution for OCaml.

But yes, you are right, these examples wouldn't be generated, unless the printer would have an option to leave out the white space, but that's admittedly a rather silly thing to have.

**Comment by prepor** [comment]
I've added some basic unit tests (and fixed a few bugs!). PRs with property based approach welcome ;)
